name: Android Test Build

on:
  workflow_dispatch:

jobs:
  test-build:
    name: Test Build Process
    runs-on: ubuntu-latest
    env:
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Decode keystore from secrets
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > app/my-release-key.jks

      - name: Build Debug APK (without signing)
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-test
          path: app/build/outputs/apk/debug/app-debug.apk 